spring:
  application:
    name: sftp-to-kafka

  kafka:
    bootstrapServers: localhost:9092
    security.protocol: PLAINTEXT
    producer:
      key:
        serializer: StringSerializer.class
      value:
        serializer: StringSerializer.class

  data:
    redis:
      host: localhost
      port: 6379
      password: my-password

app:
  target:
    topic: my-target-topic
  source:
    use: local #local | sftp
    localPath: "testData/download"
    propertyAsId: general.PATIENT_IDENTIFIER
    fileNameFilter: ".json.zip"
    pollSize: 1
    fixedDelay: 100
    sftp:
      url: localhost
      port: 2222
      username: foo
      accessKeyCertLocation:
      downloadPath: download/

